// Viseme mapping for lip sync
export const VISEME_MAP = {
    A: "viseme_PP",
    B: "viseme_kk",
    C: "viseme_I",
    D: "viseme_AA",
    E: "viseme_O",
    F: "viseme_U",
    G: "viseme_FF",
    H: "viseme_TH",
    X: "viseme_PP",
  };

// Predefined facial expressions
export const FACIAL_EXPRESSIONS = {
    default: {},
    bigSmile: {
        browInnerUp: 0.5,
        eyeSquintLeft: 0.5,
        eyeSquintRight: 0.5,
        mouthSmileLeft: 0.7,
        mouthSmileRight: 0.7,
        noseSneerLeft: 0.5,
        noseSneerRight: 0.5,
        cheekPuff: 0.2
    },
    smallSmile: {
        browInnerUp: 0.3,
        eyeSquintLeft: 0.4,
        eyeSquintRight: 0.4,
        mouthSmileLeft: 0.6,
        mouthSmileRight: 0.6,
        noseSneerLeft: 0.2,
        noseSneerRight: 0.2,
        cheekPuff: 0.2
    }
};

export const morphTargets = [
    "mouthOpen",
    "viseme_sil",
    "viseme_PP",
    "viseme_FF",
    "viseme_TH",
    "viseme_DD",
    "viseme_kk",
    "viseme_CH",
    "viseme_SS",
    "viseme_nn",
    "viseme_RR",
    "viseme_aa",
    "viseme_E",
    "viseme_I",
    "viseme_O",
    "viseme_U",
    "mouthSmile",
    "browDownLeft",
    "browDownRight",
    "browInnerUp",
    "browOuterUpLeft",
    "browOuterUpRight",
    "eyeSquintLeft",
    "eyeSquintRight",
    "eyeWideLeft",
    "eyeWideRight",
    "jawForward",
    "jawLeft",
    "jawRight",
    "mouthFrownLeft",
    "mouthFrownRight",
    "mouthPucker",
    "mouthShrugLower",
    "mouthShrugUpper",
    "noseSneerLeft",
    "noseSneerRight",
    "mouthLowerDownLeft",
    "mouthLowerDownRight",
    "mouthLeft",
    "mouthRight",
    "eyeLookDownLeft",
    "eyeLookDownRight",
    "eyeLookUpLeft",
    "eyeLookUpRight",
    "eyeLookInLeft",
    "eyeLookInRight",
    "eyeLookOutLeft",
    "eyeLookOutRight",
    "cheekPuff",
    "cheekSquintLeft",
    "cheekSquintRight",
    "jawOpen",
    "mouthClose",
    "mouthFunnel",
    "mouthDimpleLeft",
    "mouthDimpleRight",
    "mouthStretchLeft",
    "mouthStretchRight",
    "mouthRollLower",
    "mouthRollUpper",
    "mouthPressLeft",
    "mouthPressRight",
    "mouthUpperUpLeft",
    "mouthUpperUpRight",
    "mouthSmileLeft",
    "mouthSmileRight",
    "tongueOut",
    "eyeBlinkLeft",
    "eyeBlinkRight",
];
